# <center> linear regression </center>

In [1]:
import pandas as pd
df = pd.read_csv("Cleaned_Car_data.csv")
#df.iloc[row_start:row_end , col_start, col_end]
df = df.iloc[: , 1:]
df.head()

name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4              Ford Figo       Ford  2012  175000       41000    Diesel

## step-1

- check years values
- delete the inappropriate values
- change year data type



In [2]:
car = df
#car=car[car['year'].str.isnumeric()] #taking only the numeric value rows
car['year'].unique()
car['year']=car['year'].astype(int)
car['year'].info()
car['year'].unique()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: year
Non-Null Count  Dtype
--------------  -----
816 non-null    int32
dtypes: int32(1)
memory usage: 3.3 KB


array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

## step-2

- check price values
- delete inappropriate price values
- change price data type



In [3]:
car=car[car['Price']!='Ask For Price']
car['Price'].info()
car['Price'].unique()
#car['Price']=car['Price'].astype(int)

<class 'pandas.core.series.Series'>
Int64Index: 816 entries, 0 to 815
Series name: Price
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 12.8 KB


array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  285000,  340000,   70000,  289999,  849999,
        749999,  274999,  984999,  599999,  244999,  474999,  245000,
        169500,  275

## step\-3

- check kms\_driven values
- remove unnecessary kms\_driven rows
- change kms\_driven data type



In [4]:
car['kms_driven'].unique()

#car['kms_driven']=car['kms_driven'].str.split().str.get(0).str.replace(',','')
#car=car[car['kms_driven'].str.isnumeric()]

car['kms_driven']=car['kms_driven'].astype(int)
car['kms_driven'].info()
#car['kms_driven'].unique()


<class 'pandas.core.series.Series'>
Int64Index: 816 entries, 0 to 815
Series name: kms_driven
Non-Null Count  Dtype
--------------  -----
816 non-null    int32
dtypes: int32(1)
memory usage: 9.6 KB


## step\-4

- check fuel\_type values
- remove inappropriate data from fuel\_type column
- change price fuel\_type type



In [5]:
car=car[~car['fuel_type'].isna()]
car=car.reset_index(drop=True)
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                Ford Figo       Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

## step\-5

- save this new cleaned file with a new name



In [6]:
car.to_csv('Cleaned_Car_data final.csv')

In [7]:
X=car[['name','company','year','kms_driven','fuel_type']] #feature datafram
y=car['Price'] # outcome dataframe

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
from sklearn.linear_model import LinearRegression 
import numpy as np

In [10]:
ohe=OneHotEncoder() #one hot encoder applier
ohe.fit(X[['name','company','fuel_type']]) #changing categorical data to numerical

OneHotEncoder()

In [11]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')
lr=LinearRegression() #linear regression model

pipe=make_pipeline(column_trans,lr)

In [12]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2', 'Audi A6 2',
       'Audi A8 ', 'Audi Q3 2', 'Audi Q5 2', 'Audi Q7 ', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1 ', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat ', 'Chevrolet Beat Diesel',...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [16]:
X_test

name   company  year  kms_driven fuel_type
62        Tata Indigo eCS      Tata  2017      130000    Diesel
678     Audi A3 Cabriolet      Audi  2015       12516    Petrol
470     Toyota Fortuner 3    Toyota  2015      120000    Diesel
407        Nissan X Trail    Nissan  2019         300    Diesel
300  Mahindra Scorpio 2.6  Mahindra  2007      170000    Diesel
..                    ...       ...   ...         ...       ...
683   Maruti Suzuki Swift    Maruti  2009       51000    Diesel
302           Honda City      Honda  2015       39000    Petrol
792   Hyundai Santro Xing   Hyundai  2004      137495    Petrol
229       Tata Indigo eCS      Tata  2016      175400    Diesel
23     Hyundai i20 Sportz   Hyundai  2012       55000    Petrol

[164 rows x 5 columns]

In [15]:

y_pred=pipe.predict(X_test)

y_pred

array([ 3.88888120e+05,  1.18199025e+06,  9.51215779e+05,  8.29384683e+05,
        2.85855640e+05,  7.48681090e+05,  3.60399280e+05,  7.32724183e+05,
        5.23577378e+05,  2.16538675e+05,  5.65322227e+05,  2.25897547e+05,
        1.45381419e+05,  4.00898859e+05,  4.33512926e+05,  3.98489313e+05,
        1.90812848e+05,  3.88888120e+05,  2.11040964e+05,  3.85201660e+05,
        3.23028960e+05,  5.89775622e+05,  7.05871426e+04,  3.01053063e+05,
        5.40591993e+05,  5.83077582e+05,  4.85658751e+05,  1.24576957e+06,
        4.31497830e+05,  3.32272302e+05,  2.61796361e+05,  1.12010153e+06,
        5.01529070e+05, -5.20087613e+04,  1.01533442e+06,  2.57380084e+05,
        2.44282526e+06, -1.08245397e+05,  4.25073434e+05,  1.78320434e+05,
        2.91375427e+05,  1.21152889e+05,  2.22303069e+05,  4.20787776e+05,
        1.15450469e+06,  1.18880423e+05,  2.50316785e+05,  4.74457500e+05,
        6.40597155e+05,  2.78810117e+05,  7.12139497e+05,  4.08636930e+05,
        5.25070740e+05,  

In [14]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([408974.28606759])